package com.peng.mantis.model.db.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.peng.mantis.model.db.entity.TodayWeather;

import com.peng.mantis.model.db.greendao.TodayWeatherDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig todayWeatherDaoConfig;

    private final TodayWeatherDao todayWeatherDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        todayWeatherDaoConfig = daoConfigMap.get(TodayWeatherDao.class).clone();
        todayWeatherDaoConfig.initIdentityScope(type);

        todayWeatherDao = new TodayWeatherDao(todayWeatherDaoConfig, this);

        registerDao(TodayWeather.class, todayWeatherDao);
    }
    
    public void clear() {
        todayWeatherDaoConfig.clearIdentityScope();
    }

    public TodayWeatherDao getTodayWeatherDao() {
        return todayWeatherDao;
    }

}
