package com.peng.mantis.model.db.greendao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.peng.mantis.model.db.entity.TodayWeather;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "TODAY_WEATHER".
*/
public class TodayWeatherDao extends AbstractDao<TodayWeather, Void> {

    public static final String TABLENAME = "TODAY_WEATHER";

    /**
     * Properties of entity TodayWeather.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property City = new Property(0, String.class, "city", false, "CITY");
        public final static Property TodayDate = new Property(1, String.class, "todayDate", false, "TODAY_DATE");
        public final static Property Date = new Property(2, String.class, "date", false, "DATE");
        public final static Property High = new Property(3, String.class, "high", false, "HIGH");
        public final static Property Fengli = new Property(4, String.class, "fengli", false, "FENGLI");
        public final static Property Low = new Property(5, String.class, "low", false, "LOW");
        public final static Property Fengxiang = new Property(6, String.class, "fengxiang", false, "FENGXIANG");
        public final static Property Type = new Property(7, String.class, "type", false, "TYPE");
        public final static Property CacheTime = new Property(8, long.class, "cacheTime", false, "CACHE_TIME");
    }


    public TodayWeatherDao(DaoConfig config) {
        super(config);
    }
    
    public TodayWeatherDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"TODAY_WEATHER\" (" + //
                "\"CITY\" TEXT UNIQUE ," + // 0: city
                "\"TODAY_DATE\" TEXT," + // 1: todayDate
                "\"DATE\" TEXT," + // 2: date
                "\"HIGH\" TEXT," + // 3: high
                "\"FENGLI\" TEXT," + // 4: fengli
                "\"LOW\" TEXT," + // 5: low
                "\"FENGXIANG\" TEXT," + // 6: fengxiang
                "\"TYPE\" TEXT," + // 7: type
                "\"CACHE_TIME\" INTEGER NOT NULL );"); // 8: cacheTime
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"TODAY_WEATHER\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, TodayWeather entity) {
        stmt.clearBindings();
 
        String city = entity.getCity();
        if (city != null) {
            stmt.bindString(1, city);
        }
 
        String todayDate = entity.getTodayDate();
        if (todayDate != null) {
            stmt.bindString(2, todayDate);
        }
 
        String date = entity.getDate();
        if (date != null) {
            stmt.bindString(3, date);
        }
 
        String high = entity.getHigh();
        if (high != null) {
            stmt.bindString(4, high);
        }
 
        String fengli = entity.getFengli();
        if (fengli != null) {
            stmt.bindString(5, fengli);
        }
 
        String low = entity.getLow();
        if (low != null) {
            stmt.bindString(6, low);
        }
 
        String fengxiang = entity.getFengxiang();
        if (fengxiang != null) {
            stmt.bindString(7, fengxiang);
        }
 
        String type = entity.getType();
        if (type != null) {
            stmt.bindString(8, type);
        }
        stmt.bindLong(9, entity.getCacheTime());
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, TodayWeather entity) {
        stmt.clearBindings();
 
        String city = entity.getCity();
        if (city != null) {
            stmt.bindString(1, city);
        }
 
        String todayDate = entity.getTodayDate();
        if (todayDate != null) {
            stmt.bindString(2, todayDate);
        }
 
        String date = entity.getDate();
        if (date != null) {
            stmt.bindString(3, date);
        }
 
        String high = entity.getHigh();
        if (high != null) {
            stmt.bindString(4, high);
        }
 
        String fengli = entity.getFengli();
        if (fengli != null) {
            stmt.bindString(5, fengli);
        }
 
        String low = entity.getLow();
        if (low != null) {
            stmt.bindString(6, low);
        }
 
        String fengxiang = entity.getFengxiang();
        if (fengxiang != null) {
            stmt.bindString(7, fengxiang);
        }
 
        String type = entity.getType();
        if (type != null) {
            stmt.bindString(8, type);
        }
        stmt.bindLong(9, entity.getCacheTime());
    }

    @Override
    public Void readKey(Cursor cursor, int offset) {
        return null;
    }    

    @Override
    public TodayWeather readEntity(Cursor cursor, int offset) {
        TodayWeather entity = new TodayWeather( //
            cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0), // city
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // todayDate
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // date
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // high
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // fengli
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // low
            cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6), // fengxiang
            cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7), // type
            cursor.getLong(offset + 8) // cacheTime
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, TodayWeather entity, int offset) {
        entity.setCity(cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0));
        entity.setTodayDate(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setDate(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setHigh(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setFengli(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setLow(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setFengxiang(cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6));
        entity.setType(cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7));
        entity.setCacheTime(cursor.getLong(offset + 8));
     }
    
    @Override
    protected final Void updateKeyAfterInsert(TodayWeather entity, long rowId) {
        // Unsupported or missing PK type
        return null;
    }
    
    @Override
    public Void getKey(TodayWeather entity) {
        return null;
    }

    @Override
    public boolean hasKey(TodayWeather entity) {
        // TODO
        return false;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
